#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# nvm 환경 로드
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm use 20.18.0

# 원래 명령어 실행
npx --no -- commitlint --edit "$1"
