#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# nvm 환경 로드
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm use 20.18.0

# test 대신 lint 실행 또는 다른 유효한 명령어
 npm run lint  # 만약 lint 스크립트가 있다면
# 아니면 그냥 성공하도록 설정
echo "Skipping tests in pre-commit hook"
