name: Develop Branch Semantic Release

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: write      # 저장소 콘텐츠 쓰기 권한
  issues: write        # 이슈 생성 권한
  pull-requests: write # PR 관련 권한

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 git 히스토리를 가져옵니다 (semantic-release에 필요)
          persist-credentials: false  # semantic-release에서 사용자 인증 정보를 재설정합니다

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # 기본 GitHub 토큰 사용
        #           또는 개인 토큰을 사용할 경우: ${{ secrets.GH_TOKEN }}
        #          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # 필요한 경우 NPM 배포를 위한 토큰
        run: npx semantic-release
